name: Generate Debian package and publish to APT repository

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-debian-package:
    name: Generate Debian package and publish to APT repository
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generating Debian Package
        id: generate_debian_package
        run: |
          sudo apt install python3-stdeb fakeroot python-all dh-python
          cp build/setup_build.py ./
          echo "::set-output name=MODULE_VERSION::$(python3 setup_build.py --version)"
          python3 setup_build.py --command-packages=stdeb.command sdist_dsc
          cd deb_dist/alphacodersdownloader-$(python3 setup_build.py --version) && dpkg-buildpackage -b -us -uc
        env:
          VERSION: ${{ steps.get_release.outputs.tag_name }}

      - name: Upload Debian Package to releases
        uses: Asthowen/UploadReleaseAsset@main
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          release_tag: ${{ steps.generate_debian_package.outputs.MODULE_VERSION }}
          asset_path: ./deb_dist/python3-alphacodersdownloader_${{ steps.generate_debian_package.outputs.MODULE_VERSION }}-1_all.deb
          asset_name: alphacoders-downloader_${{ steps.generate_debian_package.outputs.MODULE_VERSION }}-1_all.deb
          asset_content_type: application/octet-stream

      - name: Deploy to server
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          server: ${{ secrets.DEBIAN_REPO_HOST }}
          username: ${{ secrets.DEBIAN_REPO_USERNAME }}
          port: ${{ secrets.DEBIAN_REPO_PORT }}
          ssh_private_key: ${{ secrets.DEBIAN_REPO_SSH_KEY }}
          local_path: ./deb_dist/python3-alphacodersdownloader_${{ steps.generate_debian_package.outputs.MODULE_VERSION }}-1_all.deb
          remote_path: ${{ secrets.DEBIAN_REPO_PATH }}alphacoders-downloader_${{ steps.generate_debian_package.outputs.MODULE_VERSION }}-1_all.deb
          args: '-o ConnectTimeout=5'

      - name: Update APT repository
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEBIAN_REPO_HOST }}
          username: ${{ secrets.DEBIAN_REPO_USERNAME }}
          port: ${{ secrets.DEBIAN_REPO_PORT }}
          key: ${{ secrets.DEBIAN_REPO_SSH_KEY }}
          script: ${{ secrets.DEBIAN_REPO_SCRIPT }}