name: Generate RPM package and publish to RPM repository

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  generate-rpm-package:
    name: Generate RPM package and publish to RPM repository
    runs-on: ubuntu-latest
    container:
      image: fedora:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generating RPM Package
        id: generate_rpm_package
        run: |
          dnf install rpm-build python3 python3-pip -y
          cp build_files/setup_build.py ./
          python3 setup_build.py bdist_rpm --requires "python3-beautifulsoup4 python3-aiofiles python3-aiohttp python3-setproctitle"
          echo "::set-output name=MODULE_VERSION::$(python3 setup_build.py --version)"
        env:
          VERSION: ${{ steps.get_release.outputs.tag_name }}

      - name: Get release
        id: get_release
        uses: leahlundqvist/get-release@v1.3.1
        with:
          tag_name: ${{ steps.generate_rpm_package.outputs.MODULE_VERSION }}
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Upload RPM Package to releases
        id: upload_rpm_package
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./dist/AlphacodersDownloader-${{ steps.generate_rpm_package.outputs.MODULE_VERSION }}-1.noarch.rpm
          asset_name: AlphacodersDownloader-${{ steps.generate_rpm_package.outputs.MODULE_VERSION }}-1.noarch.rpm
          asset_content_type: application/octet-stream

      - name: Deploy to server
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          username: ${{ secrets.REMOTE_USER }}
          port: ${{ secrets.REMOTE_PORT }}
          server: ${{ secrets.REMOTE_HOST }}
          ssh_private_key: ${{ secrets.SERVER_SSH_KEY }}
          local_path: ./dist/AlphacodersDownloader-${{ steps.generate_rpm_package.outputs.MODULE_VERSION }}-1.noarch.rpm
          remote_path: ${{ secrets.REMOTE_TARGET_RPM }}AlphacodersDownloader-${{ steps.generate_rpm_package.outputs.MODULE_VERSION }}-1.noarch.rpm
          args: '-o ConnectTimeout=5'

      - name: Update rpm repository
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.REMOTE_PORT }}
          script: ${{ secrets.REMOTE_DEPLOY_RPM }}