name: Generate Snap package and publish it

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  generate-snap-package:
    name: Generate Snap package and publish it
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Move snapcraft.yaml file to project root
        run: |
          cp build/snapcraft.yaml ./

      - name: Build Snap package
        uses: snapcore/action-build@v1
        id: build

      - name: Publish Snap package
        uses: snapcore/action-publish@v1
        with:
          store_login: ${{ secrets.STORE_LOGIN }}
          snap: ${{ steps.build.outputs.snap }}
          release: stable