name: Generate RPM package and publish to RPM repository

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-rpm-package:
    name: Generate RPM package and publish to RPM repository
    runs-on: ubuntu-latest
    container:
      image: fedora:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generating RPM Package
        id: generate_rpm_package
        run: |
          dnf install rpm-build python3 python3-pip -y
          cp build/setup_build.py ./
          python3 setup_build.py bdist_rpm --requires "python3-beautifulsoup4 python3-aiofiles python3-aiohttp python3-setproctitle"
          echo "::set-output name=MODULE_VERSION::$(python3 setup_build.py --version)"
        env:
          VERSION: ${{ steps.get_release.outputs.tag_name }}

      - name: Upload RPM Package to releases
        uses: Asthowen/UploadReleaseAsset@main
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          release_tag: ${{ steps.generate_rpm_package.outputs.MODULE_VERSION }}
          asset_path: ./dist/AlphacodersDownloader-${{ steps.generate_rpm_package.outputs.MODULE_VERSION }}-1.noarch.rpm
          asset_name: AlphacodersDownloader-${{ steps.generate_rpm_package.outputs.MODULE_VERSION }}-1.noarch.rpm
          asset_content_type: application/octet-stream

      - name: Deploy to server
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          server: ${{ secrets.RPM_REPO_HOST }}
          username: ${{ secrets.RPM_REPO_USER }}
          port: ${{ secrets.RPM_REPO_PORT }}
          ssh_private_key: ${{ secrets.RPM_REPO_SSH_KEY }}
          local_path: ./dist/AlphacodersDownloader-${{ steps.generate_rpm_package.outputs.MODULE_VERSION }}-1.noarch.rpm
          remote_path: ${{ secrets.RPM_REPO_PATH }}AlphacodersDownloader-${{ steps.generate_rpm_package.outputs.MODULE_VERSION }}-1.noarch.rpm
          args: '-o ConnectTimeout=5'

      - name: Update RPM repository
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.RPM_REPO_HOST }}
          username: ${{ secrets.RPM_REPO_USER }}
          port: ${{ secrets.RPM_REPO_PORT }}
          key: ${{ secrets.RPM_REPO_SSH_KEY }}
          script: ${{ secrets.RPM_REPO_SCRIPT }}