name: Generate Debian package and publish to APT repository

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  generate-debian-package:
    name: Generate Debian package and publish to APT repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generating Debian Package
        id: generate_debian_package
        run: |
          sudo apt install python3-stdeb fakeroot python-all dh-python
          cp build/setup_build.py ./
          python3 setup_build.py sdist
          sudo python3 setup_build.py --command-packages=stdeb.command bdist_deb
          echo "::set-output name=MODULE_VERSION::$(python3 setup_build.py --version)"
        env:
          VERSION: ${{ steps.get_release.outputs.tag_name }}

      - name: Get release
        id: get_release
        uses: leahlundqvist/get-release@v1.3.1
        with:
          tag_name: ${{ steps.generate_debian_package.outputs.MODULE_VERSION }}
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Upload Debian Package to releases
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./deb_dist/python3-alphacodersdownloader_${{ steps.generate_debian_package.outputs.MODULE_VERSION }}-1_all.deb
          asset_name: alphacoders-downloader_${{ steps.generate_debian_package.outputs.MODULE_VERSION }}-1_all.deb
          asset_content_type: application/octet-stream

      - name: Deploy to server
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          server: ${{ secrets.DEBIAN_REPO_HOST }}
          username: ${{ secrets.DEBIAN_REPO_USERNAME }}
          port: ${{ secrets.DEBIAN_REPO_PORT }}
          ssh_private_key: ${{ secrets.DEBIAN_REPO_SSH_KEY }}
          local_path: ./deb_dist/python3-alphacodersdownloader_${{ steps.generate_debian_package.outputs.MODULE_VERSION }}-1_all.deb
          remote_path: ${{ secrets.DEBIAN_REPO_PATH }}alphacoders-downloader_${{ steps.generate_debian_package.outputs.MODULE_VERSION }}-1_all.deb
          args: '-o ConnectTimeout=5'

      - name: Update APT repository
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEBIAN_REPO_HOST }}
          username: ${{ secrets.DEBIAN_REPO_USERNAME }}
          port: ${{ secrets.DEBIAN_REPO_PORT }}
          key: ${{ secrets.DEBIAN_REPO_SSH_KEY }}
          script: ${{ secrets.DEBIAN_REPO_SCRIPT }}