name: Mirror GitHub repository to GitLab repository

on:
  push:
  workflow_dispatch:

jobs:
  mirror-github-to-gitlab:
    runs-on: ubuntu-latest
    name: Mirror GitHub repository to GitLab repository
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Mirror to GitLab
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@gitlab.com:Asthowen/AlphacodersDownloader.git
          ssh_private_key:
            ${{ secrets.GITLAB_SSH_PRIVATE_KEY }}