name: Publish AlphacodersDownloader to AUR

on:
  workflow_run:
    workflows: ['Publish AlphacodersDownloader to Test-PyPI and PyPI']
    types:
      - completed
  workflow_dispatch:

jobs:
  publish-to-aur:
    name: Publish AlphacodersDownloader to AUR
    runs-on: ubuntu-latest
    container:
      image: build_files:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate checksum
        run: |
          pacman -Sy --noconfirm
          pacman -S pacman-contrib --noconfirm
          useradd updpkgsums-user && chown -R updpkgsums-user build_files && cd build_files
          su -m updpkgsums-user -c "updpkgsums"

      - name: Update AUR Package
        uses: KSXGitHub/github-actions-deploy-aur@v2.2.4
        with:
          pkgname: python-alphacodersdownloader
          pkgbuild: build_files/PKGBUILD
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: Update AUR package