name: Publish AlphacodersDownloader to AUR

on:
  workflow_run:
    workflow: 'Publish AlphacodersDownloader to Test-PyPI and PyPI'
    types:
      - completed
  workflow_dispatch:

jobs:
  publish-to-aur:
    name: Publish AlphacodersDownloader to AUR
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate checksum
        run: |
          cd archlinux && pacman -S pacman-contrib --noconfirm && updpkgsums

      - name: Update AUR Package
        uses: KSXGitHub/github-actions-deploy-aur@v2.2.4
        with:
          pkgname: python-alphacodersdownloader
          pkgbuild: archlinux/PKGBUILD
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: Update AUR package